-- Needs to load as soon as possible
local status, impatient = pcall(require, "impatient")

require("plugins")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.autopairs")
require("plugins.colorizer")
require("plugins.emmet")
require("plugins.elixir-tools")
require("plugins.lspconfig")
require("plugins.lspkind")
--require("plugins.lspsaga")
require("plugins.lualine")
require("plugins.mason")
require("plugins.null-ls")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.ts-autotag")
require("plugins.vim-easy-align")
require("plugins.web-devicons")
require("plugins.git-blame")

print("Jack + Joe rocks!")
