require("setup.snacks")
require("setup.noice")

require("setup.autopairs")
require("setup.colorizer")
require("setup.colors")
require("setup.conform")
require("setup.emmet")
require("setup.gitsigns")
require("setup.lspconfig")
require("setup.lspkind")
require("setup.lualine")
require("setup.mason")
require("setup.nvim-cmp")
require("setup.nvimtree")
require("setup.prettier")
require("setup.snippets")
require("setup.telescope")
require("setup.treesitter")
require("setup.ts-autotag")
require("setup.vim-easy-align")
require("setup.web-devicons")

require("setup.aider")
require("setup.codecompanion")
