[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
    # "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

# [[keyboard.bindings]]
# action = "ClearLogNotice"
# key = "L"
# mods = "Shift|Control"
#
# [[keyboard.bindings]]
# chars = "\f"
# key = "L"
# mode = "~Vi|~Search"
# mods = "Shift|Control"

# Claude Code: Use Shift+Enter for newlines
[[keyboard.bindings]]
chars = "\n"
key = "Return"
mods = "Shift"
