
[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
    # "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
]

# [[keyboard.bindings]]
# action = "ClearLogNotice"
# key = "L"
# mods = "Shift|Control"
# 
# [[keyboard.bindings]]
# chars = "\f"
# key = "L"
# mode = "~Vi|~Search"
# mods = "Shift|Control"
