#!/usr/bin/env bash

if [[ $OS == 'OSX' ]]; then
  LCTL=$HOME/Library/LaunchAgents/

  echo "Copy $@ to $LCTL"

    if [ -f $LCTL$@ ]; then
      echo "First remove old version of $@ in $LCTL"

      rm $LCTL$@
    fi

    cp $@ $LCTL$@

  echo "Load $@ in $LCTL"

    cd $LCTL

    launchctl unload $@
    launchctl load $@

    cd -
else
  echo "This will only works on OSX."

  exit 1
fi
