#!/usr/bin/env bash

if [[ `uname` == 'Darwin' ]]; then

  # OSX

  LCTL=$HOME/Library/LaunchAgents/

  echo "Copy $@ to $LCTL"

    if [ -f $LCTL$@ ]; then
      rm $LCTL$@
    fi

    cp $@ $LCTL$@

  echo "Load $@ in $LCTL"

    cd $LCTL
    launchctl load $@
    cd -

else
 
  # LINUX

  echo "This will only works on OSX."

  exit 1
fi
