export TRM=$HOME/.termieter

for config_file in $TRM/**/*.sh
do
  source $config_file
done

for function_file in $TRM/**/functions/*.sh
do
  source $function_file
done

# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

if command -v rbenv init &>/dev/null; then
  eval "$(rbenv init -)"
fi
