export TRM=$HOME/.termieter
export CURRENT_SHELL=`ps -p $$ | tail -1 | awk '{print $NF}'`
export DROPBOX=$HOME/Dropbox

if [[ `uname` == 'Darwin' ]]; then
  export OS='OSX'
else
  export OS='Linux'
fi

# LOAD ALL
for config_file in $TRM/**/*.sh
do
  source $config_file
done

for function_file in $TRM/**/functions/*.sh
do
  source $function_file
done
