# Termieter directory
export TRM=$HOME/.termieter

# Path to your oh-my-zsh configuration.
export ZSH=$TRM/zsh/oh-my-zsh

export CURRENT_SHELL=`ps -p $$ | tail -1 | awk '{print $NF}'`
export SHELL=/bin/zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

if [[ `uname` == 'Darwin' ]]; then
  # nothing yet
else
  ZSH_THEME="bira"
fi

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(gem npm rbenv)

if [[ `uname` == 'Darwin' ]]; then
  # nothing yet
else
  # plugins+=(command-not-found)
fi

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# Colors for ls and autocompletion
# eval $( gdircolors -b $ZSH/LS_COLORS )
zstyle ':completion:*:default'            list-colors ${(s.:.)LS_COLORS}

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# setopt extended_glob

# Execute
for config_file in $TRM/*/*.sh; do
  source $config_file
done

for function_file in $TRM/*/functions/*.sh; do
  source $function_file
done

alias reload!='. ~/.zshrc'
