source $HOME/.termieter/system/env

export SHELL=/bin/zsh
export ZSH=$TRM/zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

if [[ $OS == 'OSX' ]]; then
  ZSH_THEME="bira"
else
  ZSH_THEME="mortalscumbag"
fi

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# When listing options (by `setopt', `unsetopt', `set -o' or `set +o'),
# those turned on by default appear in the list prefixed with `no'.
# Hence (unless KSH_OPTION_PRINT is set), `setopt' shows all options
# whose settings are changed from the default.
#
# Report the status of background jobs immediately, rather than
# waiting until just before printing a prompt.
setopt notify 

# Print a carriage return just before printing a prompt in the line
# editor. For example:
#  $ echo foo
#  foo
#  $ echo -n foo
#  $ setopt nopromptcr
#  $ echo -n foo
#  foo$
setopt nopromptcr

# Appends every command to the history file once it is executed
setopt inc_append_history

# Reloads the history whenever you use it
setopt share_history

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(gem npm rbenv)

if [[ $OS == 'OSX' ]]; then
  # nothing yet
else
  plugins+=(git)
fi

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# Colors for ls and autocompletion
# eval $( gdircolors -b $ZSH/LS_COLORS )
zstyle ':completion:*:default'            list-colors ${(s.:.)LS_COLORS}

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# setopt extended_glob

# Execute
for config_file in $TRM/*/*.sh; do
  source $config_file
done

for function_file in $TRM/*/functions/*.sh; do
  source $function_file
done

alias reload!='. ~/.zshrc'

# RPROMPT="$RPROMPT %{$FG[098]%}[$(t | wc -l | sed -e's/ *//')]%{$reset_color%}"
