#!/bin/sh

if [ -z "$1" ]; then
  echo 'No config name / dir given!'
  echo ''
  echo 'Usage: `./install-client dir-name`'

  exit 0
fi

TARGET="$HOME/Library/Application Support/Tunnelblick/Configurations/$1"
SOURCE="`pwd`/$1/client"

if [ -d "$TARGET" ]; then
  rm -r "$TARGET"
fi

echo "Copy $SOURCE to $TARGET"

cp -R "$SOURCE" "$TARGET"

SEARCH="s/ca ca.crt/ca $1\/ca.crt/"
perl -pi -e "$SEARCH" "$TARGET/client.conf"
SEARCH="s/cert client.crt/cert $1\/client.crt/"
perl -pi -e "$SEARCH" "$TARGET/client.conf"
SEARCH="s/key client.key/key $1\/client.key/"
perl -pi -e "$SEARCH" "$TARGET/client.conf"
