PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007"'

# The simplest approach to emulate bash's $PROMPT_COMMAND
prmptcmd() { eval "$PROMPT_COMMAND" }
precmd_functions=(prmptcmd)

# Remove superfluous blanks from each command line being added to the history
# list
setopt histreduceblanks
# Remove command lines from the history list when the first character on the
# line is a space, or when one of the expanded aliases contains a leading space
setopt histignorespace
# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups

# User configuration
# Always work in a tmux session if tmux is installed
# https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
    tmux -2u attach-session -t _hack || tmux -2u new -s _hack; exit
  fi
fi

if have starship; then
  eval "$(starship init zsh)"
fi
