#!/usr/bin/env bash

export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

if [[ $OS == 'OSX' ]]; then
  export BROWSER="/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox"
  alias firefox="/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox"
else
  export BROWSER="firefox"
fi

export WEECHAT_HOME=$HOME/.config/weechat
export DROPBOX=$HOME/Dropbox
export IAMJACK="$HOME/Dropbox/iamjack"
export XDG_CONFIG_HOME="$HOME/.config"
export TERMINAL="kitty"
export FILE="nnn"
export PATH="$HOME/bin/:$PATH"
export TRMU=~/.termieter/users/jeroenb

source /Users/jeroenb/.config/broot/launcher/bash/br

. $HOME/bin/tmux.sh
