inoremap <F1> <Esc>
nmap <F1> <Nop>

color madeofme
" colorscheme landscape

if (has("termguicolors"))
  set termguicolors
endif

" suddenly I need this for ack and fzf to work (08/01/2020)
set shell=bash

" cursor line toggle
nnoremap <Leader>c :set cursorline!<CR>
nnoremap <Leader>cc :set cursorcolumn!<CR>
set cursorline

" set signcolumn=number " combine sign and number gutter

" == git (fugitive) ==================================================

nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gp :Gpush<CR>
nnoremap <leader>gl :Gpull<CR>
