#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keyboard repeate rate & compose key
xset r rate 200 90
setxkbmap -option compose:paus

~/.fehbg
 
# Take a guess
dropbox start &
 
# Notifications
dunst &

# Network applet + wireless (after dunst!)
# Not on Archius, we need nothing fancy there
host=$(hostname)
if [ "$HOST" != "$host" ]; then
  [ -x /usr/bin/nm-applet ] && nm-applet &
  [ -x /usr/bin/nmcli ] && nmcli r wifi on &
fi

# Keyboard shortcut daemon
sxhkd &

# USB auto mounting
udiskie &

# Compositor
[ -x /usr/bin/picom ] && picom &

# Status bar
slstatus &

# WM
exec startdwm
