#!/bin/sh

# Redirect errors to log file
exec 2>> ~/.xinitrc-errors.log

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f "$sysresources" ]; then
    xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]; then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keyboard repeat rate & compose key
xset r rate 200 90
setxkbmap -option compose:paus

fehbg &         # bg
snixembed &     # needed for the Dropbox App icon in the system tray...
dropbox start & # Take a guess
dunst &         # Notifications
sleep 0.5       # Let dunst initialize before starting network applet

# Network applet + wireless (after dunst!)
# Not on Archius, we need nothing fancy there
host=$(hostname)
if [ "$host" != "Archius" ]; then
  [ -x /usr/bin/nm-applet ] && nm-applet &
  [ -x /usr/bin/nmcli ] && nmcli r wifi on &
fi

sxhkd &         # Keyboard shortcut daemon
udiskie &       # USB auto mounting
slstatus &      # Status bar
conky &         # Conky stats

# WM
exec startdwm
