#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keyboard repeate rate & compose key
xset r rate 200 90
setxkbmap -option compose:paus

# Set up an icon tray
# trayer \
#   --edge top \
#   --align right \
#   --padding 6 \
#   --width 2 \
#   --transparent true \
#   --tint 0x000000 \
#   --alpha 0 \
#   --SetPartialStrut true \
#   --height 22 \
#   &

# Set a nice background
# $HOME/.fehbg &

# Network applet
# if [ -x /usr/bin/nm-applet ] ; then
#    nm-applet --sm-disable &
# fi

~/.fehbg
 
# Take a guess
dropbox start &
 
# Notifications
dunst &

# Keyboard shortcut daemon
sxhkd &

# USB auto mounting
udiskie &

dwmstatus &

# WM
exec startdwm
