#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config window_border_placement      interior
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xaa0289ff
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.7
yabai -m config window_opacity_duration      0.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10

# rules
yabai -m rule --add app="kitty" space=1
yabai -m rule --add app="Kitty" space=1
yabai -m rule --add app="*kitty*" space=1
yabai -m rule --add app="*Kitty*" space=1
yabai -m rule --add app="iTerm2" space=1
yabai -m rule --add app="^Firefox*" space=2
yabai -m rule --add app="^Firefox*" title="^Opening .*$" manage=off
yabai -m rule --add app="^Firefox*" title="^File Upload$" manage=off
yabai -m rule --add app="Mail" space=3
yabai -m rule --add app="Spotify" space=5 manage=off
# grid=8:8:0:1:1:1
yabai -m rule --add app="^Copy$" manage=off sticky=on layer=above
yabai -m rule --add app="^System Preferences$" manage=off sticky=on layer=above
yabai -m rule --add app="^Karabiner-Elements$" manage=off sticky=on layer=above
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off sticky=on layer=above
yabai -m rule --add app="^Alfred Preferences$" manage=off sticky=on layer=above
yabai -m rule --add app="^System Information$" manage=off sticky=on layer=above
yabai -m rule --add app=Preview manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Trello" space=4
yabai -m rule --add app="Slack" space=4
yabai -m rule --add app="TablePlus" space=3
# yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="^GIMP*" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="QuickTime Player" manage=off
yabai -m rule --add app="Harvest" manage=off
yabai -m rule --add app="zoom.us" manage=off
yabai -m rule --add  app="VirtualBox" manage=off
yabai -m rule --add  app="VirtualBox VM" manage=off

echo "yabai configuration loaded..."
