if [[ $OS == 'OSX' ]]; then
  export QT_QPA_PLATFORMTHEME="qt5ct"
  export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
  export GDK_SCALE=2 
  export GDK_DPI_SCALE=0.5
  export BROWSER="/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox"
  alias firefox="/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox"
else
  export BROWSER="firefox"
fi

export WEECHAT_HOME=$HOME/.config/weechat
export DROPBOX=$HOME/Dropbox
export IAMJACK="$HOME/Dropbox/iamjack"
export XDG_CONFIG_HOME="$HOME/.config"
export TERMINAL="kitty"
export FILE="nnn"
export PATH="$HOME/bin/:$PATH"
export TRMU=~/.termieter/users/jeroenb

export FLYCTL_INSTALL="/home/jeroen/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

alias pbcopy='xclip -selection clipboard'

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# rupa z
. $TRMU/bin/z.sh

[ -f "/Users/jeroenb/.ghcup/env" ] && source "/Users/jeroenb/.ghcup/env" # ghcup-env
