ZSH_THEME="kolo"

set LC_ALL="en_US.UTF-8"

PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007"'

# The simplest approach to emulate bash's $PROMPT_COMMAND
prmptcmd() { eval "$PROMPT_COMMAND" }
precmd_functions=(prmptcmd)

# User configuration
# Always work in a tmux session if tmux is installed
# https://github.com/chrishunt/dot-files/blob/master/.zshrc
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color" ] && [ $TERM != "screen" ]; then
    tmux attach -t _hack || tmux new -s _hack; exit
  fi
fi
